export const fancy_styles = [
    {
        name: 'Script (مخطوطة)',
        transform: (/** @type {any} */ text) => {
            const scriptMap = {
                a: '𝒶',
                b: '𝒷',
                c: '𝒸',
                d: '𝒹',
                e: '𝑒',
                f: '𝒻',
                g: '𝑔',
                h: '𝒽',
                i: '𝒾',
                j: '𝒿',
                k: '𝓀',
                l: '𝓁',
                m: '𝓂',
                n: '𝓃',
                o: '𝑜',
                p: '𝓅',
                q: '𝓆',
                r: '𝓇',
                s: '𝓈',
                t: '𝓉',
                u: '𝓊',
                v: '𝓋',
                w: '𝓌',
                x: '𝓍',
                y: '𝓎',
                z: '𝓏',
                A: '𝒜',
                B: 'ℬ',
                C: '𝒞',
                D: '𝒟',
                E: 'ℰ',
                F: 'ℱ',
                G: '𝒢',
                H: 'ℋ',
                I: 'ℐ',
                J: '𝒥',
                K: '𝒦',
                L: 'ℒ',
                M: 'ℳ',
                N: '𝒩',
                O: '𝒪',
                P: '𝒫',
                Q: '𝒬',
                R: 'ℛ',
                S: '𝒮',
                T: '𝒯',
                U: '𝒰',
                V: '𝒱',
                W: '𝒲',
                X: '𝒳',
                Y: '𝒴',
                Z: '𝒵',
                0: '0',
                1: '1',
                2: '2',
                3: '3',
                4: '4',
                5: '5',
                6: '6',
                7: '7',
                8: '8',
                9: '9',
            }
            return [...text].map(char => scriptMap[char] || char).join('')
        },
    },
    {
        name: 'Double-struck (مزدوج)',
        transform: (/** @type {any} */ text) => {
            const doubleStruckMap = {
                a: '𝕒',
                b: '𝕓',
                c: '𝕔',
                d: '𝕕',
                e: '𝕖',
                f: '𝕗',
                g: '𝕘',
                h: '𝕙',
                i: '𝕚',
                j: '𝕛',
                k: '𝕜',
                l: '𝕝',
                m: '𝕞',
                n: '𝕟',
                o: '𝕠',
                p: '𝕡',
                q: '𝕢',
                r: '𝕣',
                s: '𝕤',
                t: '𝕥',
                u: '𝕦',
                v: '𝕧',
                w: '𝕨',
                x: '𝕩',
                y: '𝕪',
                z: '𝕫',
                A: '𝔸',
                B: '𝔹',
                C: 'ℂ',
                D: '𝔻',
                E: '𝔼',
                F: '𝔽',
                G: '𝔾',
                H: 'ℍ',
                I: '𝕀',
                J: '𝕁',
                K: '𝕂',
                L: '𝕃',
                M: '𝕄',
                N: 'ℕ',
                O: '𝕆',
                P: 'ℙ',
                Q: 'ℚ',
                R: 'ℝ',
                S: '𝕊',
                T: '𝕋',
                U: '𝕌',
                V: '𝕍',
                W: '𝕎',
                X: '𝕏',
                Y: '𝕐',
                Z: 'ℤ',
                0: '𝟘',
                1: '𝟙',
                2: '𝟚',
                3: '𝟛',
                4: '𝟜',
                5: '𝟝',
                6: '𝟞',
                7: '𝟟',
                8: '𝟠',
                9: '𝟡',
            }
            return [...text].map(char => doubleStruckMap[char] || char).join('')
        },
    },
    {
        name: 'Fraktur (قوطي)',
        transform: (/** @type {any} */ text) => {
            const frakturMap = {
                a: '𝔞',
                b: '𝔟',
                c: '𝔠',
                d: '𝔡',
                e: '𝔢',
                f: '𝔣',
                g: '𝔤',
                h: '𝔥',
                i: '𝔦',
                j: '𝔧',
                k: '𝔨',
                l: '𝔩',
                m: '𝔪',
                n: '𝔫',
                o: '𝔬',
                p: '𝔭',
                q: '𝔮',
                r: '𝔯',
                s: '𝔰',
                t: '𝔱',
                u: '𝔲',
                v: '𝔳',
                w: '𝔴',
                x: '𝔵',
                y: '𝔶',
                z: '𝔷',
                A: '𝔄',
                B: '𝔅',
                C: 'ℭ',
                D: '𝔇',
                E: '𝔈',
                F: '𝔉',
                G: '𝔊',
                H: 'ℌ',
                I: 'ℑ',
                J: '𝔍',
                K: '𝔎',
                L: '𝔏',
                M: '𝔐',
                N: '𝔑',
                O: '𝔒',
                P: '𝔓',
                Q: '𝔔',
                R: 'ℜ',
                S: '𝔖',
                T: '𝔗',
                U: '𝔘',
                V: '𝔙',
                W: '𝔚',
                X: '𝔛',
                Y: '𝔜',
                Z: 'ℨ',
                0: '0',
                1: '1',
                2: '2',
                3: '3',
                4: '4',
                5: '5',
                6: '6',
                7: '7',
                8: '8',
                9: '9',
            }
            return [...text].map(char => frakturMap[char] || char).join('')
        },
    },
    {
        name: 'Circled (دائري)',
        transform: (/** @type {any} */ text) => {
            const circledMap = {
                a: 'ⓐ',
                b: 'ⓑ',
                c: 'ⓒ',
                d: 'ⓓ',
                e: 'ⓔ',
                f: 'ⓕ',
                g: 'ⓖ',
                h: 'ⓗ',
                i: 'ⓘ',
                j: 'ⓙ',
                k: 'ⓚ',
                l: 'ⓛ',
                m: 'ⓜ',
                n: 'ⓝ',
                o: 'ⓞ',
                p: 'ⓟ',
                q: 'ⓠ',
                r: 'ⓡ',
                s: 'ⓢ',
                t: 'ⓣ',
                u: 'ⓤ',
                v: 'ⓥ',
                w: 'ⓦ',
                x: 'ⓧ',
                y: 'ⓨ',
                z: 'ⓩ',
                A: 'Ⓐ',
                B: 'Ⓑ',
                C: 'Ⓒ',
                D: 'Ⓓ',
                E: 'Ⓔ',
                F: 'Ⓕ',
                G: 'Ⓖ',
                H: 'Ⓗ',
                I: 'Ⓘ',
                J: 'Ⓙ',
                K: 'Ⓚ',
                L: 'Ⓛ',
                M: 'Ⓜ',
                N: 'Ⓝ',
                O: 'Ⓞ',
                P: 'Ⓟ',
                Q: 'Ⓠ',
                R: 'Ⓡ',
                S: 'Ⓢ',
                T: 'Ⓣ',
                U: 'Ⓤ',
                V: 'Ⓥ',
                W: 'Ⓦ',
                X: 'Ⓧ',
                Y: 'Ⓨ',
                Z: 'Ⓩ',
                0: '⓪',
                1: '①',
                2: '②',
                3: '③',
                4: '④',
                5: '⑤',
                6: '⑥',
                7: '⑦',
                8: '⑧',
                9: '⑨',
            }
            return [...text].map(char => circledMap[char] || char).join('')
        },
    },
    {
        name: 'Full-width (عريض)',
        transform: (/** @type {any} */ text) => {
            const fullWidthMap = {
                a: 'ａ',
                b: 'ｂ',
                c: 'ｃ',
                d: 'ｄ',
                e: 'ｅ',
                f: 'ｆ',
                g: 'ｇ',
                h: 'ｈ',
                i: 'ｉ',
                j: 'ｊ',
                k: 'ｋ',
                l: 'ｌ',
                m: 'ｍ',
                n: 'ｎ',
                o: 'ｏ',
                p: 'ｐ',
                q: 'ｑ',
                r: 'ｒ',
                s: 'ｓ',
                t: 'ｔ',
                u: 'ｕ',
                v: 'ｖ',
                w: 'ｗ',
                x: 'ｘ',
                y: 'ｙ',
                z: 'ｚ',
                A: 'Ａ',
                B: 'Ｂ',
                C: 'Ｃ',
                D: 'Ｄ',
                E: 'Ｅ',
                F: 'Ｆ',
                G: 'Ｇ',
                H: 'Ｈ',
                I: 'Ｉ',
                J: 'Ｊ',
                K: 'Ｋ',
                L: 'Ｌ',
                M: 'Ｍ',
                N: 'Ｎ',
                O: 'Ｏ',
                P: 'Ｐ',
                Q: 'Ｑ',
                R: 'Ｒ',
                S: 'Ｓ',
                T: 'Ｔ',
                U: 'Ｕ',
                V: 'Ｖ',
                W: 'Ｗ',
                X: 'Ｘ',
                Y: 'Ｙ',
                Z: 'Ｚ',
                0: '０',
                1: '１',
                2: '２',
                3: '３',
                4: '４',
                5: '５',
                6: '６',
                7: '７',
                8: '８',
                9: '９',
                ' ': '　',
                '!': '！',
                '"': '＂',
                '#': '＃',
                $: '＄',
                '%': '％',
                '&': '＆',
                "'": '＇',
                '(': '（',
                ')': '）',
                '*': '＊',
                '+': '＋',
                ',': '，',
                '-': '－',
                '.': '．',
                '/': '／',
                ':': '：',
                ';': '；',
                '<': '＜',
                '=': '＝',
                '>': '＞',
                '?': '？',
                '@': '＠',
                '[': '［',
                '\\': '＼',
                ']': '］',
                '^': '＾',
                _: '＿',
                '`': '｀',
                '{': '｛',
                '|': '｜',
                '}': '｝',
                '~': '～',
            }
            return [...text].map(char => fullWidthMap[char] || char).join('')
        },
    },
    {
        name: 'Small Caps (أحرف صغيرة)',
        transform: (/** @type {any} */ text) => {
            const smallCapsMap = {
                a: 'ᴀ',
                b: 'ʙ',
                c: 'ᴄ',
                d: 'ᴅ',
                e: 'ᴇ',
                f: 'ꜰ',
                g: 'ɢ',
                h: 'ʜ',
                i: 'ɪ',
                j: 'ᴊ',
                k: 'ᴋ',
                l: 'ʟ',
                m: 'ᴍ',
                n: 'ɴ',
                o: 'ᴏ',
                p: 'ᴘ',
                q: 'ǫ',
                r: 'ʀ',
                s: 's',
                t: 'ᴛ',
                u: 'ᴜ',
                v: 'ᴠ',
                w: 'ᴡ',
                x: 'x',
                y: 'ʏ',
                z: 'ᴢ',
            }
            return [...text]
                .map(char => {
                    const lowerChar = char.toLowerCase()
                    return smallCapsMap[lowerChar] || char
                })
                .join('')
        },
    },
]

export const unicodeDatabase = {
    0x0628: {
        name: 'ARABIC LETTER BEH',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0627: {
        name: 'ARABIC LETTER ALEF',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x062a: {
        name: 'ARABIC LETTER TEH',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x062b: {
        name: 'ARABIC LETTER THEH',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x062c: {
        name: 'ARABIC LETTER JEEM',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x062d: {
        name: 'ARABIC LETTER HAH',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x062e: {
        name: 'ARABIC LETTER KHAH',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x062f: {
        name: 'ARABIC LETTER DAL',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0630: {
        name: 'ARABIC LETTER THAL',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0631: {
        name: 'ARABIC LETTER REH',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0632: {
        name: 'ARABIC LETTER ZAIN',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0633: {
        name: 'ARABIC LETTER SEEN',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0634: {
        name: 'ARABIC LETTER SHEEN',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0635: {
        name: 'ARABIC LETTER SAD',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0636: {
        name: 'ARABIC LETTER DAD',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0637: {
        name: 'ARABIC LETTER TAH',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0638: {
        name: 'ARABIC LETTER ZAH',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0639: {
        name: 'ARABIC LETTER AIN',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x063a: {
        name: 'ARABIC LETTER GHAIN',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0641: {
        name: 'ARABIC LETTER FEH',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0642: {
        name: 'ARABIC LETTER QAF',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0643: {
        name: 'ARABIC LETTER KAF',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0644: {
        name: 'ARABIC LETTER LAM',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0645: {
        name: 'ARABIC LETTER MEEM',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0646: {
        name: 'ARABIC LETTER NOON',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0647: {
        name: 'ARABIC LETTER HEH',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0648: {
        name: 'ARABIC LETTER WAW',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x0649: {
        name: 'ARABIC LETTER ALEF MAKSURA',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x064a: {
        name: 'ARABIC LETTER YEH',
        category: 'Lo',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    0x064b: {
        name: 'ARABIC FATHATAN',
        category: 'Mn',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    0x064c: {
        name: 'ARABIC DAMMATAN',
        category: 'Mn',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    0x064d: {
        name: 'ARABIC KASRATAN',
        category: 'Mn',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    0x064e: {
        name: 'ARABIC FATHA',
        category: 'Mn',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    0x064f: {
        name: 'ARABIC DAMMA',
        category: 'Mn',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    0x0650: {
        name: 'ARABIC KASRA',
        category: 'Mn',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    0x0651: {
        name: 'ARABIC SHADDA',
        category: 'Mn',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    0x0652: {
        name: 'ARABIC SUKUN',
        category: 'Mn',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
}

export const arabic_chars_data = [
    {
        char: 'ء',
        code: 0x0621,
        name: 'همزة',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER HAMZA',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {
            ayah: 'إِنَّ الَّذِينَ كَفَرُوا سَوَاءٌ عَلَيْهِمْ أَأَنْذَرْتَهُمْ أَمْ لَمْ تُنْذِرْهُمْ لَا يُؤْمِنُونَ',
            surah: 'البقرة',
            number: 6,
        },
    },
    {
        char: 'آ',
        code: 0x0622,
        name: 'ألف مد',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER ALEF WITH MADDA ABOVE',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {
            ayah: 'آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ',
            surah: 'البقرة',
            number: 285,
        },
    },
    {
        char: 'أ',
        code: 0x0623,
        name: 'ألف همزة',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER ALEF WITH HAMZA ABOVE',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {ayah: 'أَفَلَا يَعْقِلُونَ', surah: 'يس', number: 68},
    },
    {
        char: 'ؤ',
        code: 0x0624,
        name: 'واو همزة',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER WAW WITH HAMZA ABOVE',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {
            ayah: 'وَإِذْ غَدَوْتَ مِنْ أَهْلِكَ تُبَوِّئُ الْمُؤْمِنِينَ مَقَاعِدَ لِلْقِتَالِ ۗ وَاللَّهُ سَمِيعٌ عَلِيمٌ',
            surah: 'آل عمران',
            number: 121,
        },
    },
    {
        char: 'إ',
        code: 0x0625,
        name: 'ألف همزة أسفل',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER ALEF WITH HAMZA BELOW',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {ayah: 'إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ', surah: 'الكوثر', number: 1},
    },
    {
        char: 'ئ',
        code: 0x0626,
        name: 'ياء همزة',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER YEH WITH HAMZA ABOVE',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {ayah: '', surah: '', number: 85},
    },
    {
        char: 'ا',
        code: 0x0627,
        name: 'ألف',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER ALEF',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {ayah: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ', surah: 'البقرة', number: 255},
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        orthography: 'both',
    },
    {
        char: 'ب',
        code: 0x0628,
        name: 'باء',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER BEH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        combining: false,
        ayah_example: {ayah: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ', surah: 'الفاتحة', number: 1},
    },
    {
        char: 'ة',
        code: 0x0629,
        name: 'تاء مربوطة',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER TEH MARBUTA',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {
            ayah: 'الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ وَيُقِيمُونَ الصَّلَاةَ وَمِمَّا رَزَقْنَاهُمْ يُنْفِقُونَ',
            surah: 'البقرة',
            number: 3,
        },
    },
    {
        char: 'ت',
        code: 0x062a,
        name: 'تاء',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER TEH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {
            ayah: 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
            surah: 'الفاتحة',
            number: 5,
        },
    },
    {
        char: 'ث',
        code: 0x062b,
        name: 'ثاء',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER THEH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {
            ayah: 'ثُمَّ تَوَلَّيْتُمْ مِنْ بَعْدِ ذَٰلِكَ ۖ فَلَوْلَا فَضْلُ اللَّهِ عَلَيْكُمْ وَرَحْمَتُهُ لَكُنْتُمْ مِنَ الْخَاسِرِينَ',
            surah: 'البقرة',
            number: 64,
        },
    },
    {
        char: 'ج',
        code: 0x062c,
        name: 'جيم',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER JEEM',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {ayah: '', surah: '', number: 85},
    },
    {
        char: 'ح',
        code: 0x062d,
        name: 'حاء',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER HAH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {
            ayah: 'أُولَٰئِكَ الَّذِينَ اشْتَرَوُا الضَّلَالَةَ بِالْهُدَىٰ فَمَا رَبِحَتْ تِجَارَتُهُمْ وَمَا كَانُوا مُهْتَدِينَ',
            surah: 'البقرة',
            number: 16,
        },
    },
    {
        char: 'خ',
        code: 0x062e,
        name: 'خاء',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER KHAH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {ayah: 'خَلَقَ الْإِنسَانَ مِنْ عَلَقٍ', surah: 'العلق', number: 2},
    },
    {
        char: 'د',
        code: 0x062f,
        name: 'دال',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER DAL',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {ayah: 'لَكُم دِينِكُمْ وَلِيَ دِينِ', surah: 'الكافرون', number: 6},
    },
    {
        char: 'ذ',
        code: 0x0630,
        name: 'ذال',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER THAL',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {ayah: 'ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ', surah: 'البقرة', number: 2},
    },
    {
        char: 'ر',
        code: 0x0631,
        name: 'راء',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER REH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {ayah: 'رَبِّ اشْرَحْ لِي صَدْرِي', surah: 'طه', number: 25},
    },
    {
        char: 'ز',
        code: 0x0632,
        name: 'زاي',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER ZAIN',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {ayah: 'زُيِّنَ لِلنَّاسِ حُبُّ الشَّهَوَاتِ', surah: 'آل عمران', number: 14},
    },
    {
        char: 'س',
        code: 0x0633,
        name: 'سين',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER SEEN',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {ayah: 'سُبْحَانَ اللَّهِ عَمَّا يَصِفُونَ', surah: 'الصافات', number: 159},
    },
    {
        char: 'ش',
        code: 0x0634,
        name: 'شين',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER SHEEN',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {
            ayah: 'شَهِدَ اللَّهُ أَنَّهُ لَا إِلَٰهَ إِلَّا هُوَ',
            surah: 'آل عمران',
            number: 18,
        },
    },
    {
        char: 'ص',
        code: 0x0635,
        name: 'صاد',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER SAD',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {
            ayah: 'صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ',
            surah: 'الفاتحة',
            number: 7,
        },
    },
    {
        char: 'ض',
        code: 0x0636,
        name: 'ضاد',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER DAD',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {ayah: 'وَضُحَاهَا', surah: 'الشمس', number: 1},
    },
    {
        char: 'ط',
        code: 0x0637,
        name: 'طاء',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER TAH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {ayah: 'طَهٰ', surah: 'طه', number: 1},
    },
    {
        char: 'ظ',
        code: 0x0638,
        name: 'ظاء',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER ZAH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {ayah: 'وَظَنَّ دَاوُودُ أَنَّمَا فَتَنَّاهُ', surah: 'ص', number: 24},
    },
    {
        char: 'ع',
        code: 0x0639,
        name: 'عين',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER AIN',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {ayah: 'عَلَّمَ الْإِنسَانَ مَا لَمْ يَعْلَمْ', surah: 'العلق', number: 5},
    },
    {
        char: 'غ',
        code: 0x063a,
        name: 'غين',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER GHAIN',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        ayah_example: {ayah: 'غَافِرِ الذَّنْبِ وَقَابِلِ التَّوْبِ', surah: 'غافر', number: 3},
    },
    {
        char: 'ـ',
        code: 0x0640,
        name: 'تطويل',
        category: 'Lm',
        unicode_name: 'ARABIC TATWEEL',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'ف',
        code: 0x0641,
        name: 'فاء',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER FEH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {ayah: 'فَاذْكُرُونِي أَذْكُرْكُمْ', surah: 'البقرة', number: 152},
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        orthography: 'sharqi', // Sharqi: dot above
    },
    {
        char: 'ڢ',
        code: 0x06a2,
        name: 'فاء مغربي',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER FEH WITH DOT BELOW',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        orthography: 'maghribi', // Maghribi: dot below
    },
    {
        char: 'ق',
        code: 0x0642,
        name: 'قاف',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER QAF',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {ayah: 'قُلْ هُوَ اللَّهُ أَحَدٌ', surah: 'الإخلاص', number: 1},
        riwayat: ['common', 'hafs', 'warsh', 'qaloon'],
        orthography: 'sharqi', // Sharqi: two dots above
    },
    {
        char: 'ڧ',
        code: 0x06a7,
        name: 'قاف مغربي',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER QAF WITH ONE DOT ABOVE',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        orthography: 'maghribi', // Maghribi: one dot above
    },
    {
        char: 'ك',
        code: 0x0643,
        name: 'كاف',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER KAF',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {ayah: 'كُلُّ نَفْسٍ ذَائِقَةُ الْمَوْتِ', surah: 'آل عمران', number: 185},
    },
    {
        char: 'ل',
        code: 0x0644,
        name: 'لام',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER LAM',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {ayah: 'لَا إِلَٰهَ إِلَّا اللَّهُ', surah: 'الصافات', number: 35},
    },
    {
        char: 'م',
        code: 0x0645,
        name: 'ميم',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER MEEM',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {ayah: 'مَالِكِ يَوْمِ الدِّينِ', surah: 'الفاتحة', number: 4},
    },
    {
        char: 'ن',
        code: 0x0646,
        name: 'نون',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER NOON',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {ayah: 'ن وَالْقَلَمِ وَمَا يَسْطُرُونَ', surah: 'القلم', number: 1},
    },
    {
        char: 'ه',
        code: 0x0647,
        name: 'هاء',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER HEH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {
            ayah: 'هُوَ اللَّهُ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ',
            surah: 'الحشر',
            number: 22,
        },
    },
    {
        char: 'و',
        code: 0x0648,
        name: 'واو',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER WAW',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {ayah: 'وَالْعَصْرِ', surah: 'العصر', number: 1},
    },
    {
        char: 'ى',
        code: 0x0649,
        name: 'ألف مقصورة',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER ALEF MAKSURA',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {ayah: 'وَالضُّحَىٰ', surah: 'الضحى', number: 1},
    },
    {
        char: 'ي',
        code: 0x064a,
        name: 'ياء',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER YEH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {
            ayah: 'إِنَّمَا ٱلْمُؤْمِنُونَ إِخْوَةٌۭ فَأَصْلِحُوا۟ بَيْنَ أَخَوَيْكُمْ',
            surah: 'الحجرات',
            number: 10,
        },
    },
    {
        char: 'ً',
        code: 0x064b,
        name: 'فتحتان',
        category: 'Mn',
        unicode_name: 'ARABIC FATHATAN',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'وَٱهْجُرْهُمْ هَجْرًۭا جَمِيلًۭا',
            surah: 'المزمل',
            number: 10,
        },
    },
    {
        char: 'ٌ',
        code: 0x064c,
        name: 'ضمتان',
        category: 'Mn',
        unicode_name: 'ARABIC DAMMATAN',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'وَفَتْحٌۭ قَرِيبٌۭ',
            surah: 'الصف',
            number: 13,
        },
    },
    {
        char: 'ٍ',
        code: 0x064d,
        name: 'كسرتان',
        category: 'Mn',
        unicode_name: 'ARABIC KASRATAN',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'وَطَعَامًا ذَا غُصَّةٍ وَعَذَابًا أَلِيمًا',
            surah: 'المزمل',
            number: 13,
        },
    },
    {
        char: 'َ',
        code: 0x064e,
        name: 'فتحة',
        category: 'Mn',
        unicode_name: 'ARABIC FATHA',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'ٱقْرَأْ بِٱسْمِ رَبِّكَ ٱلَّذِى خَلَقَ',
            surah: 'العلق',
            number: 1,
        },
    },
    {
        char: 'ُ',
        code: 0x064f,
        name: 'ضمة',
        category: 'Mn',
        unicode_name: 'ARABIC DAMMA',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'قُتِلَ ٱلْإِنسَٰنُ مَآ أَكْفَرَهُۥ',
            surah: 'عبس',
            number: 17,
        },
    },
    {
        char: 'ِ',
        code: 0x0650,
        name: 'كسرة',
        category: 'Mn',
        unicode_name: 'ARABIC KASRA',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
            surah: 'الفاتحة',
            number: 1,
        },
    },
    {
        char: 'ّ',
        code: 0x0651,
        name: 'شدة',
        category: 'Mn',
        unicode_name: 'ARABIC SHADDA',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'إِيَّاكَ نَعْبُدُ',
            surah: 'الفاتحة',
            number: 5,
        },
    },
    {
        char: 'ْ',
        code: 0x0652,
        name: 'سكون',
        category: 'Mn',
        unicode_name: 'ARABIC SUKUN',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'لَمْ يَلِدْ وَلَمْ يُولَدْ',
            surah: 'الإخلاص',
            number: 3,
        },
    },
    {
        char: 'ٓ',
        code: 0x0653,
        name: 'مدة',
        category: 'Mn',
        unicode_name: 'ARABIC MADDAH ABOVE',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'ءَامَنَ ٱلرَّسُولُ بِمَآ أُنزِلَ إِلَيْهِ',
            surah: 'البقرة',
            number: 285,
        },
    },
    {
        char: 'ٔ',
        code: 0x0654,
        name: 'همزة فوق',
        category: 'Mn',
        unicode_name: 'ARABIC HAMZA ABOVE',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'يَسْـَٔلُونَكَ عَنِ ٱلْأَهِلَّةِ',
            surah: 'البقرة',
            number: 189,
        },
    },
    {
        char: 'ٕ',
        code: 0x0655,
        name: 'همزة تحت',
        category: 'Mn',
        unicode_name: 'ARABIC HAMZA BELOW',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {ayah: 'إِنِّىٓ أَنَا ٱللَّهُ', surah: 'طه', number: 14},
    },
    {
        char: '٠',
        code: 0x0660,
        name: 'صفر',
        category: 'Nd',
        unicode_name: 'ARABIC-INDIC DIGIT ZERO',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: false,
    },
    {
        char: '١',
        code: 0x0661,
        name: 'واحد',
        category: 'Nd',
        unicode_name: 'ARABIC-INDIC DIGIT ONE',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: false,
    },
    {
        char: '٢',
        code: 0x0662,
        name: 'اثنان',
        category: 'Nd',
        unicode_name: 'ARABIC-INDIC DIGIT TWO',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: false,
    },
    {
        char: '٣',
        code: 0x0663,
        name: 'ثلاثة',
        category: 'Nd',
        unicode_name: 'ARABIC-INDIC DIGIT THREE',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: false,
    },
    {
        char: '٤',
        code: 0x0664,
        name: 'أربعة',
        category: 'Nd',
        unicode_name: 'ARABIC-INDIC DIGIT FOUR',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: false,
    },
    {
        char: '٥',
        code: 0x0665,
        name: 'خمسة',
        category: 'Nd',
        unicode_name: 'ARABIC-INDIC DIGIT FIVE',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: false,
    },
    {
        char: '٦',
        code: 0x0666,
        name: 'ستة',
        category: 'Nd',
        unicode_name: 'ARABIC-INDIC DIGIT SIX',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: false,
    },
    {
        char: '٧',
        code: 0x0667,
        name: 'سبعة',
        category: 'Nd',
        unicode_name: 'ARABIC-INDIC DIGIT SEVEN',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: false,
    },
    {
        char: '٨',
        code: 0x0668,
        name: 'ثمانية',
        category: 'Nd',
        unicode_name: 'ARABIC-INDIC DIGIT EIGHT',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: false,
    },
    {
        char: '٩',
        code: 0x0669,
        name: 'تسعة',
        category: 'Nd',
        unicode_name: 'ARABIC-INDIC DIGIT NINE',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: false,
    },
    {
        char: '،',
        code: 0x060c,
        name: 'فاصلة عربية',
        category: 'Po',
        unicode_name: 'ARABIC COMMA',
        bidi: 'Arabic Letter',
        script: 'Arabic',
        combining: false,
    },
    {
        char: '؛',
        code: 0x061b,
        name: 'فاصلة منقوطة عربية',
        category: 'Po',
        unicode_name: 'ARABIC SEMICOLON',
        bidi: 'Arabic Letter',
        script: 'Arabic',
        combining: false,
    },
    {
        char: '؟',
        code: 0x061f,
        name: 'علامة استفهام عربية',
        category: 'Po',
        unicode_name: 'ARABIC QUESTION MARK',
        bidi: 'Arabic Letter',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'ﷲ',
        code: 0xfdf2,
        name: 'لفظ الجلالة',
        category: 'Lo',
        unicode_name: 'ARABIC LIGATURE ALLAH ISOLATED FORM',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {
            ayah: '﻿بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
            surah: 'الفاتحة',
            number: 1,
        },
    },
    {
        char: 'ﷺ',
        code: 0xfdfa,
        name: 'صلى الله عليه وسلم',
        category: 'So',
        unicode_name: 'ARABIC LIGATURE SALLALLAHOU ALAYHE WASALLAM',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'ﷻ',
        code: 0xfdfb,
        name: 'جل جلاله',
        category: 'So',
        unicode_name: 'ARABIC LIGATURE JALLAJALALOUHOU',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    {
        char: '۝',
        code: 0x06dd,
        name: 'رمز آية',
        category: 'Cf',
        unicode_name: 'ARABIC END OF AYAH',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: false,
    },
    {
        char: '۞',
        code: 0x06de,
        name: 'رمز حزب',
        category: 'So',
        unicode_name: 'ARABIC START OF RUB EL HIZB',
        bidi: 'Other Neutral',
        script: 'Arabic',
        combining: false,
        ayah_example: {
            ayah: '۞ وَيَطُوفُ عَلَيْهِمْ غِلْمَانٌ لَهُمْ كَأَنَّهُمْ لُؤْلُؤٌ مَكْنُونٌ',
            surah: 'الطور',
            number: 24,
        },
    },
    {
        char: 'ݐ',
        code: 0x0750,
        name: 'باء ثلاث نقاط فوق',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER BEH WITH THREE DOTS HORIZONTALLY BELOW',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'ݑ',
        code: 0x0751,
        name: 'باء ثلاث نقاط تحت',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER BEH WITH DOT BELOW AND THREE DOTS ABOVE',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'ﻻ',
        code: 0xfefb,
        name: 'لام ألف',
        category: 'Lo',
        unicode_name: 'ARABIC LIGATURE LAM WITH ALEF ISOLATED FORM',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {
            ayah: 'صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',
            surah: 'الفاتحة',
            number: 7,
        },
    },
    {
        char: 'ﻷ',
        code: 0xfef7,
        name: 'لام ألف همزة فوق',
        category: 'Lo',
        unicode_name: 'ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE ISOLATED FORM',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'ﻹ',
        code: 0xfef9,
        name: 'لام ألف همزة تحت',
        category: 'Lo',
        unicode_name: 'ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW ISOLATED FORM',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'پ',
        code: 0x067e,
        name: 'باء ثلاث نقاط',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER PEH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'چ',
        code: 0x0686,
        name: 'تشيم',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER TCHEH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'ژ',
        code: 0x0698,
        name: 'الزاي الغليظة',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER JEH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'گ',
        code: 0x06af,
        name: 'كاف فارسي',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER GAF',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'ٹ',
        code: 0x0679,
        name: 'تاء طويلة',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER TTEH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'ڈ',
        code: 0x0688,
        name: 'دال طويلة',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER DDAL',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'ڑ',
        code: 0x0691,
        name: 'راء طويلة',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER RREH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    {
        char: '۩',
        code: 0x06e9,
        name: 'علامة سجدة',
        category: 'So',
        unicode_name: 'ARABIC PLACE OF SAJDAH',
        bidi: 'Other Neutral',
        script: 'Arabic',
        combining: false,
        ayah_example: {
            ayah: 'يَا أَيُّهَا الَّذِينَ آمَنُوا ارْكَعُوا وَاسْجُدُوا وَاعْبُدُوا رَبَّكُمْ وَافْعَلُوا الْخَيْرَ لَعَلَّكُمْ تُفْلِحُونَ ۩',
            surah: 'الحج',
            number: 77,
        },
    },
    {
        char: '﴾',
        code: 0xfd3e,
        name: 'قوس زخرفي يمين',
        category: 'Pe',
        unicode_name: 'ORNATE LEFT PARENTHESIS',
        bidi: 'Other Neutral',
        script: 'Common',
        combining: false,
    },
    {
        char: '﴿',
        code: 0xfd3f,
        name: 'قوس زخرفي يسار',
        category: 'Ps',
        unicode_name: 'ORNATE RIGHT PARENTHESIS',
        bidi: 'Other Neutral',
        script: 'Common',
        combining: false,
    },
    {
        char: 'ٱ',
        code: 0x0671,
        name: 'ألف وصل',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER ALEF WASLA',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {
            ayah: '﻿بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
            surah: 'الفاتحة',
            number: 1,
        },
    },
    {
        char: 'ی',
        code: 0x06cc,
        name: 'ياء فارسية',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER FARSI YEH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'ٰ',
        code: 0x0670,
        name: 'ألف خنجرية',
        category: 'Mn',
        unicode_name: 'ARABIC LETTER SUPERSCRIPT ALEF',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'قِيلَ يَا نُوحُ اهْبِطْ بِسَلَامٍ مِنَّا وَبَرَكَاتٍ عَلَيْكَ وَعَلَىٰ أُمَمٍ مِمَّنْ مَعَكَ ۚ وَأُمَمٌ سَنُمَتِّعُهُمْ ثُمَّ يَمَسُّهُمْ مِنَّا عَذَابٌ أَلِيمٌ',
            surah: 'هود',
            number: 48,
        },
    },
    {
        char: 'ۡ',
        code: 0x0621,
        name: 'س خاء صغيرة',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL HIGH DOTLESS HEAD OF KHAH',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'وَمَثَلُهُمْ فِي الْإِنْجِيلِ كَزَرْعٍ أَخْرَجَ شَطْأَهُ فَآزَرَهُ فَاسْتَغْلَظَ فَاسْتَوَىٰ عَلَىٰ سُوقِهِ يُعْجِبُ الزُّرَّاعَ لِيَغِيظَ بِهِمُ الْكُفَّارَ ۗ',
            surah: 'الفتح',
            number: 29,
        },
    },
    {
        char: '۟',
        code: 0x06df,
        name: 'صفر علوي صغير مدور',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL HIGH ROUNDED ZERO',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'ۤ',
        code: 0x06e4,
        name: 'مدة صغيرة',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL HIGH MADDA',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'ۖ',
        code: 0x06d6,
        name: 'صاد صغيرة',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL FATHA',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'مُحَمَّدٌ رَسُولُ اللَّهِ ۚ وَالَّذِينَ مَعَهُ أَشِدَّاءُ عَلَى الْكُفَّارِ رُحَمَاءُ بَيْنَهُمْ ۖ تَرَاهُمْ رُكَّعًا سُجَّدًا يَبْتَغُونَ فَضْلًا مِنَ اللَّهِ وَرِضْوَانًا ۖ',
            surah: 'الفتح',
            number: 29,
        },
    },
    {
        char: 'ۗ',
        code: 0x06d7,
        name: 'قاف صغيرة',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL DAMMA',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'فَآزَرَهُ فَاسْتَغْلَظَ فَاسْتَوَىٰ عَلَىٰ سُوقِهِ يُعْجِبُ الزُّرَّاعَ لِيَغِيظَ بِهِمُ الْكُفَّارَ ۗ وَعَدَ اللَّهُ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ مِنْهُمْ مَغْفِرَةً وَأَجْرًا عَظِيمًا',
            surah: 'الفتح',
            number: 29,
        },
    },
    {
        char: 'ۚ',
        code: 0x06da,
        name: 'جيم صغيرة',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL WAW',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'مُحَمَّدٌ رَسُولُ اللَّهِ ۚ وَالَّذِينَ مَعَهُ أَشِدَّاءُ عَلَى الْكُفَّارِ رُحَمَاءُ بَيْنَهُمْ ۖ تَرَاهُمْ رُكَّعًا سُجَّدًا يَبْتَغُونَ فَضْلًا مِنَ اللَّهِ وَرِضْوَانًا ۖ',
            surah: 'الفتح',
            number: 29,
        },
    },
    {
        char: 'ۘ',
        code: 0x06d8,
        name: 'ميم صغيرة',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL MEEM',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: '۞ إِنَّ اللَّهَ لَا يَسْتَحْيِي أَنْ يَضْرِبَ مَثَلًا مَا بَعُوضَةً فَمَا فَوْقَهَا ۚ فَأَمَّا الَّذِينَ آمَنُوا فَيَعْلَمُونَ أَنَّهُ الْحَقُّ مِنْ رَبِّهِمْ ۖ وَأَمَّا الَّذِينَ كَفَرُوا فَيَقُولُونَ مَاذَا أَرَادَ اللَّهُ بِهَٰذَا مَثَلًا ۘ يُضِلُّ بِهِ كَثِيرًا وَيَهْدِي بِهِ كَثِيرًا ۚ وَمَا يُضِلُّ بِهِ إِلَّا الْفَاسِقِينَ',
            surah: 'البقرة',
            number: 26,
        },
    },
    {
        char: 'ۛ',
        code: 0x06db,
        name: 'ثلاث نقاط علوية',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL THREE DOTS',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'ۜ',
        code: 0x06dc,
        name: 'سين صغيرة',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL HIGH SEEN',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'ۣ',
        code: 0x06e3,
        name: 'سين منخفضة صغيرة',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL LOW SEEN',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'ۥ',
        code: 0x06e5,
        name: 'واو صغيرة',
        category: 'Lm',
        unicode_name: 'ARABIC SMALL WAW',
        bidi: 'Arabic Letter',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'ࣳ',
        code: 0x08f3,
        name: 'واو صغيرة علوية',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL HIGH WAW',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'ۦ',
        code: 0x06e6,
        name: 'ياء صغيرة',
        category: 'Lm',
        unicode_name: 'ARABIC SMALL YEH',
        bidi: 'Arabic Letter',
        script: 'Arabic',
        combining: false,
    },
    {
        char: 'ۧ',
        code: 0x06e7,
        name: 'ياء صغيرة علوية',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL HIGH YEH',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'ۭ',
        code: 0x06ed,
        name: 'ميم صغيرة منخفضة',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL LOW MEEM',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'ۢ',
        code: 0x06e2,
        name: 'ميم صغيرة',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL HIGH MEEM',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'ۨ',
        code: 0x06e8,
        name: 'نون صغيرة',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL HIGH NOON',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: '۠',
        code: 0x06e0,
        name: 'صفر مستطيل علوي صغير',
        category: 'Mn',
        unicode_name: 'ARABIC SMALL HIGH UPRIGHT RECTANGULAR ZERO',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'ے',
        code: 0x06d2,
        name: 'ياء فارسية',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER YEH BARREE',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {
            ayah: 'اَ۬للَّهُ يَسْتَهْزِۓُ بِهِمْ وَيَمُدُّهُمْ فِے طُغْيَٰنِهِمْ يَعْمَهُونَۖ',
            surah: 'البقرة',
            number: 14,
        },
        riwayat: ['warsh'],
        orthography: 'maghribi',
    },
    {
        char: 'ٞ',
        code: 0x065e,
        name: 'فتح عربي بنقطتين',
        category: 'Lo',
        unicode_name: 'ARABIC FATHA WITH TWO DOTS',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {
            ayah: 'وَقُلۡنَا اَ۪هۡبِطُواْ بَعۡضُكُمۡ لِبَعۡضٍ عَدُوّٞۖ وَلَكُمۡ فِي اِ۬لۡأَرۡضِ مُسۡتَقَرّٞ وَمَتَٰعٌ إِلَىٰ حِينٖ',
            surah: 'البقرة',
            number: 35,
        },
        riwayat: ['warsh', 'douri'],
        orthography: 'maghribi',
    },
    {
        char: '۪',
        code: 0x06ea,
        name: 'مركز فارغ منخفض',
        category: 'Lo',
        unicode_name: 'ARABIC EMPTY CENTER LOW STOP',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        ayah_example: {
            ayah: 'أُوْلَٰٓئِكَ اَ۬لذِينَ اَ۪شْتَرَوُاْ اُ۬لضَّلَٰلَةَ بِالْهُد۪ىٰ',
            surah: 'البقرة',
            number: 14,
        },
        riwayat: ['warsh'],
        orthography: 'maghribi',
    },
    {
        char: 'ٮ',
        code: 0x066e,
        name: 'باء بدون نقاط',
        category: 'Lo',
        unicode_name: 'ARABIC LETTER DOTLESS BEH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        orthography: 'maghribi',
    },
    {
        char: 'ٖ',
        code: 0x0656,
        name: 'الألف العربية السفلية',
        category: 'Lo',
        unicode_name: 'ARABIC SUBSCRIPT ALEF',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        orthography: 'maghribi',
    },
    {
        char: 'ٗ',
        code: 0x0657,
        name: 'ضمة عربية معكوسة',
        category: 'Lo',
        unicode_name: 'ARABIC INVERTED DAMMA',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        orthography: 'maghribi',
    },
    {
        char: '٘',
        code: 0x0658,
        name: 'ضمة عربية معكوسة',
        category: 'Lo',
        unicode_name: 'ARABIC MARK NOON GHUNNAH',
        bidi: 'Right-To-Left',
        script: 'Arabic',
        combining: false,
        orthography: 'maghribi',
    },
    {
        char: 'ٜ',
        code: 0x065c,
        name: 'علامة عربية نون غنة',
        category: 'Mn',
        unicode_name: 'ARABIC VOWEL SIGN DOT BELOW',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'ٙ',
        code: 0x0659,
        name: 'علامة عربية زواراكاي',
        category: 'Mn',
        unicode_name: 'ARABIC ZWARAKAY',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'ٚ',
        code: 0x065a,
        name: 'علامة حرف العلة العربية حرف V صغير أعلاه',
        category: 'Mn',
        unicode_name: 'ARABIC VOWEL SIGN SMALL V ABOVE',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'ٛ',
        code: 0x065b,
        name: 'علامة حرف العلة العربية المقلوبة V الصغيرة',
        category: 'Mn',
        unicode_name: 'ARABIC VOWEL SIGN INVERTED SMALL V ABOVE',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'ٝ',
        code: 0x065d,
        name: 'علامة ضمة مقلوبة',
        category: 'Mn',
        unicode_name: 'ARABIC REVERSED DUMMA',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'ٟ',
        code: 0x065f,
        name: 'علامة همزة منحنية',
        category: 'Mn',
        unicode_name: 'ARABIC WAVY HAMZA BELOW',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: '۬',
        code: 0x06ec,
        name: 'نقطة علوية صغيرة',
        category: 'Mn',
        unicode_name: 'ARABIC ROUNDED HIGH STOP WITH FILLED CENTRE',
        bidi: 'Arabic Number',
        script: 'Arabic',
        combining: true,
    },
    {
        char: 'مَجۡرٜىٰهَا',
        name: '',
        category: 'Mn',
        unicode_name: '',
        bidi: '',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: '۞ وَقَالَ ارْكَبُوا فِيهَا بِسْمِ اللَّهِ مَجْرَاهَا وَمُرْسَاهَا ۚ إِنَّ رَبِّي لَغَفُورٌ رَحِيمٌ',
            surah: 'هود',
            number: 41,
        },
    },
    {
        char: 'تَأۡمَ۬نَّا',
        name: '',
        category: 'Mn',
        unicode_name: '',
        bidi: '',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'قَالُوا يَا أَبَانَا مَا لَكَ لَا تَأْمَنَّا عَلَىٰ يُوسُفَ وَإِنَّا لَهُ لَنَاصِحُونَ',
            surah: 'يوسف',
            number: 11,
        },
    },
    {
        char: 'ءَا۬عۡجَمِیࣱّ',
        name: '',
        category: 'Mn',
        unicode_name: '',
        bidi: '',
        script: 'Arabic',
        combining: true,
        ayah_example: {
            ayah: 'وَلَوْ جَعَلْنَاهُ قُرْآنًا أَعْجَمِيًّا لَقَالُوا لَوْلَا فُصِّلَتْ آيَاتُهُ ۖ أَأَعْجَمِيٌّ وَعَرَبِيٌّ ۗ قُلْ هُوَ لِلَّذِينَ آمَنُوا هُدًى وَشِفَاءٌ ۖ وَالَّذِينَ لَا يُؤْمِنُونَ فِي آذَانِهِمْ وَقْرٌ وَهُوَ عَلَيْهِمْ عَمًى ۚ أُولَٰئِكَ يُنَادَوْنَ مِنْ مَكَانٍ بَعِيدٍ',
            surah: 'فصلت',
            number: 44,
        },
    },
]
