[tools]
node = '22'
pnpm = '9'
lefthook = 'latest'

[tasks.build]
run = 'pnpm install && pnpm build'

[tasks.deploy]
depends = ['build']
run = 'scp -C dist/index.html $DEPLOY_HOST:/srv/apps/toolsapp'
